server:
  port: 8081

spring:
  application:
    name: user-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:7080/realms/ride-hailing-realm
          jwk-set-uri: http://localhost:7080/realms/ride-hailing-realm/protocol/openid-connect/certs
  datasource:
    url: jdbc:postgresql://127.0.0.1:5433/ride_hailing
    username: admin
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

keycloak:
  auth-server-url: http://localhost:7080
  realm: ride-hailing-realm
  admin:
    username: admin
    password: admin
    client-id: admin-cli
  client-id: ride-hailing-gateway
  client-secret: YOUR_CLIENT_SECRET # Not needed if public

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces
