server:
  port: 8084

spring:
  application:
    name: location-service
  data:
    redis:
      host: 127.0.0.1
      port: 6380

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
